### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'handle_unknown'

### ISSUE THREAD

**Issue by bigcharless** [abhishekkrthakur/autoxgb#2]
Hey I got this error and no idea where it is from. My manual xgb model works without problems with exactly the same dataset.

I have no idea how to use github so sorry if this does not match your standards.

<img width="883" alt="Capture d’écran 2021-10-31 à 17 34 28" src="https://user-images.githubusercontent.com/61186675/139593495-c296f1f2-cdcb-42b4-bc78-4616fc9831d3.png">

**Comment by abhishekkrthakur** [comment]
It seems like you are using an older version of scikit-learn. please update to >=1.0.1

**Comment by bigcharless** [comment]
That was it. Well spotted, upgrading sklearn solves the problem.

**Comment by abhishekkrthakur** [comment]
Glad that worked!
