### ISSUE TITLE
local variable 'test_pred_temp' referenced before assignment

### ISSUE THREAD

**Issue by melnimr** [abhishekkrthakur/autoxgb#5]
I am getting:

local variable 'test_pred_temp' referenced before assignment

**Comment by melnimr** [comment]
These are my parameters:

**Comment by abhishekkrthakur** [comment]
is there an example notebook i can look at?

**Comment by melnimr** [comment]
It is very simple this all I am doing:
from autoxgb import AutoXGB


# required parameters:
train_filename = "input.csv"
output = "output"

# optional parameters
test_filename = None
task = None
idx = None
targets = ["L0_L","L0_Q"]
features = None
categorical_features = None
use_gpu = False
num_folds = 5
seed = 42
num_trials = 10
time_limit = 360
fast = False

%%time
axgb = AutoXGB(
    train_filename=train_filename,
    output=output,
    test_filename=test_filename,
    task=task,
    idx=idx,
    targets=targets,
    features=features,
    categorical_features=categorical_features,
    use_gpu=use_gpu,
    num_folds=num_folds,
    seed=seed,
    num_trials=num_trials,
    time_limit=time_limit,
    fast=fast,
)
axgb.train()

**Comment by abhishekkrthakur** [comment]
i don't know what `["L0_L","L0_Q"]` consist of so I don't know which task is detected. 
If you can provide more details as to what is the problem type and the full stacktrace, I might be able to help and fix the issue :)

**Comment by melnimr** [comment]
Yeah, sure. Sorry.:
2021-11-03 09:42:42.637 | INFO     | autoxgb.utils:optimize:192 - Metrics: {'r2': 0.01016874926611211, 'mse': 4.36942834854126, 'mae': 1.170691442489624, 'rmse': 1.478068971633911}
[I 2021-11-03 09:42:42,651] Trial 2 finished with value: 1.478068971633911 and parameters: {'learning_rate': 0.05627011727078463, 'reg_lambda': 0.3836558454452216, 'reg_alpha': 6.231161136117104e-08, 'subsample': 0.9271543868294292, 'colsample_bytree': 0.66180182404386, 'max_depth': 3, 'early_stopping_rounds': 373, 'n_estimators': 15000, 'tree_method': 'hist', 'booster': 'gblinear'}. Best is trial 1 with value: 0.9232276558876038.
2021-11-03 09:52:58.084 | INFO     | autoxgb.utils:optimize:192 - Metrics: {'r2': 0.49635667365699465, 'mse': 0.03250111043453217, 'mae': 0.09907760620117187, 'rmse': 0.12754933536052704}
[I 2021-11-03 09:52:58,103] Trial 3 finished with value: 0.12754933536052704 and parameters: {'learning_rate': 0.02946768943017482, 'reg_lambda': 3.3666103096872506e-08, 'reg_alpha': 15.365822442258114, 'subsample': 0.7794683947200962, 'colsample_bytree': 0.913571808934958, 'max_depth': 2, 'early_stopping_rounds': 497, 'n_estimators': 15000, 'tree_method': 'approx', 'booster': 'gbtree', 'gamma': 0.0001905389675134395, 'grow_policy': 'depthwise'}. Best is trial 3 with value: 0.12754933536052704.
2021-11-03 09:52:58.108 | INFO     | autoxgb.autoxgb:train:248 - Training complete
2021-11-03 09:52:58.109 | INFO     | autoxgb.autoxgb:predict:252 - Creating OOF and test predictions
2021-11-03 09:52:58.109 | INFO     | autoxgb.utils:predict_model:238 - Training and predicting for fold 0

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<timed exec> in <module>

~/wellth-wrk/env/lib/python3.8/site-packages/autoxgb/autoxgb.py in train(self)
    247         best_params = train_model(self.model_config)
    248         logger.info("Training complete")
--> 249         self.predict(best_params)
    250 
    251     def predict(self, best_params):

~/wellth-wrk/env/lib/python3.8/site-packages/autoxgb/autoxgb.py in predict(self, best_params)
    251     def predict(self, best_params):
    252         logger.info("Creating OOF and test predictions")
--> 253         predict_model(self.model_config, best_params)

~/wellth-wrk/env/lib/python3.8/site-packages/autoxgb/utils.py in predict_model(model_config, best_params)
    283 
    284                 ypred.append(ypred_temp)
--> 285                 test_pred.append(test_pred_temp)
    286 
    287             ypred = np.column_stack(ypred)

UnboundLocalError: local variable 'test_pred_temp' referenced before assignment



and the variables have the following stats:


  | L0_n | L0_r
-- | -- | --
159200.000000 | 159200.000000
3.502500 | 0.000066
1.734128 | 0.000016
0.500000 | 0.000030
2.000000 | 0.000054
3.500000 | 0.000068
5.000000 | 0.000079
6.500000 | 0.000090

**Comment by abhishekkrthakur** [comment]
Thank you very much. I've fixed the issue in latest pip version. Please update with `pip install -U autoxgb`. Please let me know if this fixes your issue :)

**Comment by abhishekkrthakur** [comment]
@melnimr if the new release fixes your issue, please let me know.

**Comment by melnimr** [comment]
Thanks, it fixed yet,closing this.
